/*
 * N5g_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (s://openapi-generator.tech)
 */

package sbi

import (
	"net/http"

	"github.com/gin-gonic/gin"

	// "github.com/free5gc/openapi"
	// "github.com/free5gc/openapi/models"
	// // eir_context "github.com/adjivas/eir/internal/context"
	"github.com/adjivas/eir/internal/logger"
	// "github.com/adjivas/eir/internal/util"
)

func (s *Server) getDataRepositoryRoutes() []Route {
	return []Route{
		{
			"Index",
			"GET",
			"/",
			Index,
		},
		{
			"EquipementStatus",
			"GET",
			"/equipement-status",
			s.HandleQueryEirEquipementStatus,
		},
	}
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusNotImplemented, "Hello World!")
}

func (s *Server) HandleQueryEirEquipementStatus(c *gin.Context) {
	logger.DataRepoLog.Tracef("Handle EirEquipementStatus")

	c.String(http.StatusNotImplemented, "Hello World 43!")
}
