/*
 * N5g_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (s://openapi-generator.tech)
 */

package sbi

import (
	"net/http"

	"github.com/gin-gonic/gin"

	// "github.com/free5gc/openapi"
	"github.com/free5gc/openapi/models"
	// // eir_context "github.com/adjivas/eir/internal/context"
	"github.com/adjivas/eir/internal/logger"
	// "github.com/adjivas/eir/internal/util"
)

func (s *Server) getDataRepositoryRoutes() []Route {
	return []Route{
		{
			"Index",
			"GET",
			"/",
			Index,
		},
		{
			"EquipementStatus",
			"GET",
			"/equipement-status",
			s.HandleQueryEirEquipementStatus,
		},
	}
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusNotImplemented, "Hello World!")
}

func (s *Server) HandleQueryEirEquipementStatus(c *gin.Context) {
	logger.DataRepoLog.Tracef("Handle EirEquipementStatus")

	pei := c.Query("pei")
	supi := c.Query("supi")
	gpsi := c.Query("gpsi")
	logger.MainLog.Infof("ADJIVAS Log enable is set to %v %v %v", pei, supi, gpsi)

    // c.JSON(200, gin.H{
    //     "status": "WHITELISTED",
    // })
    //

	problemDetail := models.ProblemDetails{
		Title: "Not found",
		Status: http.StatusNotFound,
		Detail: "Supi not found",
		Cause:  "ERROR_EQUIPMENT_UNKNOWN",
	}
	// logger.CallbackLog.Errorf("Get Request Body error: %+v", "Supi not found")
	c.JSON(http.StatusNotFound, problemDetail)
}
