info:
  version: 1.1.0
  description: EIR initial local configuration

configuration:
  defaultStatus: "WHITELISTED"
  metrics:
    scheme: http
    bindingIPv4: "127.0.0.1"
    port: 9095
    tls:
      pem: cert/eir.pem
      key: cert/eir.key
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    oauth: false
    registerIP: 127.0.0.54 # IP used to register to NRF
    bindingIP: 127.0.0.54  # IP used to bind the service
    # registerIP: "2001:db8::1:0:0:7" # IP used to register to NRF
    # bindingIP: "2001:db8::1:0:0:7"  # IP used to bind the service
    port: 8000 # port used to bind the service
    tls: # the local path of TLS key
      pem: cert/eir.pem # EIR TLS Certificate
      key: cert/eir.key # EIR TLS Private key
  dbConnectorType: mongodb 
  mongodb:
    name: free5gc # Database name in MongoDB
    url: mongodb://localhost:27017 # URL of MongoDB
  nrfUri: http://127.0.0.10:8000 # a valid URI of NRF
  nrfCertPem: cert/nrf.pem # NRF Certificate

logger: # log output setting
  enable: true # true or false
  level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  reportCaller: false # enable the caller report or not, value: true or false
